### ISSUE TITLE
possible to extend to multiple ds18b20

### ISSUE THREAD

**Issue by saiaman** [stonatm/UiFlow-custom-blocks#1]
Is there a way to add : 
- list ds18b20 devices
- get device temp by Index
etc etc ?

Or maybe i can code this if you explain me what tool i can use to code?

**Comment by stonatm** [comment]
Yes, there is such a possibility. But because of my assumptions while creating custom blocks. The code had to be as short as possible because it had to be placed in the custom block to avoid additional manual uploading of libraries to which the custom block would refer. From the uiflow editor level there is no possibility to upload selected files other than m5f, jpg or bmp

Generally you can upload the file to the block editor
http://block-maker.m5stack.com/
Upload the m5b file and there you can view and edit each block and what code is injected where each block occurs. All of the "library" code is placed in the init block as a class definition to separate it from the rest of the code created automatically by the uiflow editor. The rest of the blocks refer to the appropriate functions contained in this class.

I put the file with the code I based on (blocky18b20.py) in the repository.
